"""add_description

Revision ID: 5b4a88ad57dc
Revises: 7b887594a8d9
Create Date: 2025-05-06 20:54:40.762786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b4a88ad57dc'
down_revision: Union[str, None] = '7b887594a8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineevent', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineevent', 'description')
    # ### end Alembic commands ###
